# Generated by Django 3.1.7 on 2021-09-24 11:38

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django_extensions.db.fields
import scripts.keygen


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=300, null=True, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=300, null=True, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=300, null=True, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=300, null=True, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('turkish_title', models.CharField(max_length=300)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('listz_id', models.CharField(default=scripts.keygen.KeyGenerator.generate_unique_key, max_length=25)),
                ('year', models.CharField(blank=True, max_length=25)),
                ('imdb_rating', models.CharField(blank=True, max_length=10)),
                ('certificate', models.CharField(blank=True, max_length=10)),
                ('runtime', models.CharField(blank=True, max_length=25)),
                ('stars', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('plot', models.TextField(blank=True, max_length=500)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('votes', models.CharField(blank=True, max_length=12)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'year'])),
                ('vector_column', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('actors', models.ManyToManyField(blank=True, to='recommender.Actor')),
                ('countries', models.ManyToManyField(blank=True, to='recommender.Country')),
                ('directors', models.ManyToManyField(blank=True, to='recommender.Director')),
                ('genres', models.ManyToManyField(blank=True, to='recommender.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(blank=True, to='recommender.Movie'),
        ),
        migrations.AddField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(blank=True, to='recommender.Movie'),
        ),
        migrations.AddField(
            model_name='country',
            name='movies',
            field=models.ManyToManyField(blank=True, to='recommender.Movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, to='recommender.Movie'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='recommender_vector__0a7d3c_gin'),
        ),
    ]
