# Generated by Django 3.1.7 on 2021-09-24 11:38

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommender', '0001_initial'),
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['user__username', 'title'], unique=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following_watchlists', to='authz.Profile')),
                ('movies', models.ManyToManyField(blank=True, to='recommender.Movie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='authz.profile')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Common', 'Common'), ('Editor', 'Editor'), ('Personalized', 'Personalized')], max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['title'], unique=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='admin_lists', to='recommender.Movie')),
            ],
        ),
    ]
